### ISSUE TITLE
Request: short var name for "Library"

### ISSUE THREAD

**Issue by LauraNicolas** [RasmusTidselbak/al-var-helper#1]
Hello Rasmus, 

Thanks for this great extension! I use it for naming my vars and it is very helpful.

When preparing my test codeunits, I create a lot of variables to use the Test Libraries.
May I ask if you could add the following rule for short naming:
**Library    > Lib**

Thanks a lot.

Salut!
Laura Nicolàs

**Comment by RasmusTidselbak** [comment]
Hi Laura,

Thank you for the suggestion, I will add it asap.
