### ISSUE TITLE
Casing issues

### ISSUE THREAD

**Issue by jwikman** [RasmusTidselbak/al-var-helper#10]
I've noticed a few places where the "Fix casing" changes casing in the wrong way:

1. In Page object, "action(" element changes to "Action(", should remain "action" (I guess that it matches for Action::LookupOK)
1. In Page object, SourceTableView property, "SORTING" should change to "sorting", does not change
1. In Report object, DataItemTableView property, "SORTING" should change to "sorting", does not change
1. In Page object, SourceTableView property, "where" changes to "Where", shoud be "where"
1. "STRSUBSTNO" changes to "StrSubStNo", should be "StrSubstNo"
1. "RecordId" changes to "RecordID", should stay "RecordId"
1. "RecRef.Field" changes to "RecRef.field", should stay "RecRef.Field"
1. Datatype "label" should be changed to "Label"
1. "Next" as a value in an option string becomes "Next()", should stay as "Next (this one has resulted in really strange errors):
`procedure SetColumns(SetWanted: Option Initial,Previous,Same,Next,PreviousColumn,NextColumn);` and `ActionChangePeriods(gSetWanted::Next);`
becomes `procedure SetColumns(SetWanted: Option Initial,Previous,Same,Next(),PreviousColumn,NextColumn);` and `ActionChangePeriods(gSetWanted::Next());`

1. "modify" in a Page Extension layout changes to "Modify", should stay "modify"
` layout
    {
        Modify("Job No.")
` should stay `
 layout
    {
        modify("Job No.")
`
1. Page field TableRelation "where" changes to "Where", should stay "where" 
`TableRelation = Job Where ("Whatever" = field ("Whatever"));`
1. Report DataItemTableView "where" changes to "Where", should stay "where" 
1. "downto" in for statement changes to "DownTo", should stay "downto"
1. "COPYSTR" should change to "CopyStr", does not change
1. "EVALUATE" should change to "Evaluate", does not change
1. "SELECTSTR" should change to "SelectStr", does not change
1. "PageVariable.EDITABLE" should change to "PageVariable.Editable", does not change
1. "Record.CALCSUMS" should change to "Record.CalcSums", does not change
1. "FIELDERROR(" should change to "FieldError("
1. "ROUND(" should change to "Round("

That was what I found in my code right now, but I got the feeling that it's even more. ;-)

But overall it's doing a great job!

Maybe you should look into fin.stx to find all keyword that might need to be changed?

**Comment by RasmusTidselbak** [comment]
I'll look into it, thanks alot for the very thorough description :)

**Comment by jwikman** [comment]
20. "FIELDCAPTION" should change to "FieldCaption"
:)
