### ISSUE TITLE
Can't get variables

### ISSUE THREAD

**Issue by swoonhusker1** [RasmusTidselbak/al-var-helper#11]
I'm sorry I must be doing something wrong. I just installed the extension and have not used VS Code as much as other powershell editors. I liked the detailed view of all variables in PowerGUI, so I installed this extension in VS Code with hopes that I could view my local/global variables without having to figure out the debugger (which I had issues with).

I read the usage of AL Variable Helper and it says to use CTRL + L or CTRL + G to view your local/global variables, but when I have my script open and I hit these keys, I get this message- 
![image](https://user-images.githubusercontent.com/47569583/53684183-d1f67e80-3ccf-11e9-85e4-b5a02cc71c8a.png)
It says "command 'alvarhelper.LocalVars' not found"

Is there something easy I am missing?
Thank you so much for any help you can provide!

**Comment by RasmusTidselbak** [comment]
The extension is for editing .al files only, it won't help you get variable values during debugging.

Can you elaborate on what you are doing when the error appear?

**Comment by swoonhusker1** [comment]
Okay, maybe I'm using it wrong. I was editing a .ps1 file with VS Code. I pressed CTRL + L on the keyboard and they error came up.
