### ISSUE TITLE
Some casing issue

### ISSUE THREAD

**Issue by matteomontanari** [RasmusTidselbak/al-var-helper#12]
Hi

local variable
"Skip: Boolean;" has been mistakenly converted to "Skip(): Boolean;"

".MODIFY(" should be ".Modify("
"DATABASE::" should be "database::"
"SETAUTOCALCFIELDS" should be "SetAutoCalcFields"
"UNTIL " should be "until "
".MODIFYALL(" should be ".ModifyAll("
"STRMENU(" should be "StrMenu("
".CLOSE()" should be ".Close()"
"GETRANGEMIN(" should be "GetRangeMin("
"GETRANGEMAX(" should be "GetRangeMax("
"COMPRESSARRAY" should be "CompressArray"

Matteo

**Comment by RasmusTidselbak** [comment]
Fixed in next release, thank you for the suggestion
