### ISSUE TITLE
Feature request: AL Suffix

### ISSUE THREAD

**Issue by ichladil** [RasmusTidselbak/al-var-helper#15]
Both prefixes and suffices are allowed in object names in AL development. 
As a developer I would like both prefixes and suffixes to be removed from variable names. 

I.e. having add-on prefix = XXX I would like both names _MyObject XXX_ and _XXX MyObject_ to result in _MyObject_ variable name. 

Your extension already supports _Ignore ALPrefix_. Could you please change its behaviour to prefix/suffix or introduce another property for Ignore ALSuffix?

Thanks!

**Comment by RasmusTidselbak** [comment]
Got it, added new option to ignore Suffix
