### ISSUE TITLE
XmlPorts issues

### ISSUE THREAD

**Issue by YannRobertCargo** [RasmusTidselbak/al-var-helper#16]
Hello,
Thanks for the neat extension !
Here's an issue I found. In an XmlPort, the "fix casing" function will change the "UseRequestPage" property into "UseRequestPage()". It should not.

![image](https://user-images.githubusercontent.com/47186314/59432927-bf203980-8de8-11e9-885e-a370446de615.png)

Also, the "Sort variables" function will sort an XmlPort after pages when it should be before.
![image](https://user-images.githubusercontent.com/47186314/59433655-4c17c280-8dea-11e9-90ad-a1bde3e0a2c2.png)
![image](https://user-images.githubusercontent.com/47186314/59433699-5fc32900-8dea-11e9-8c46-c1a4df813049.png)

**Comment by RasmusTidselbak** [comment]
I'll look into it.

**Comment by RasmusTidselbak** [comment]
Fixed in next release
