### ISSUE TITLE
Fix variable sorting order

### ISSUE THREAD

**Issue by ChrisBlankDe** [RasmusTidselbak/al-var-helper#17]
I think TypeWeight should be fixed.
When using Sort Variables it generates a Warning about wrong order.

> Variable declarations should be ordered by type. Variables should be sorted like this: Record, Report, Codeunit, XmlPort, Page, Query, Notification, BigText, DateFormula, RecordId, RecordRef, FieldRef, and FilterPageBuilder. The rest of the variables are not sorted.AL(AA0021)

Order after Sort:
Record, Page, Codeunit
Expected order:
Record, Codeunit, Page

https://github.com/RasmusTidselbak/al-var-helper/blob/a06658d22da2c7b21ac9b3c67705402f9e13a672/client/src/components/variable.ts#L92

**Comment by RasmusTidselbak** [comment]
Fixed in next release.
