### ISSUE TITLE
Omit prefix when creating variable name.

### ISSUE THREAD

**Issue by cvale** [RasmusTidselbak/al-var-helper#2]
We have a prefix registered with Microsoft, and objects now have very stupid names, example "XXX Post Budget Journal". Is it possible to add configuration for prefix (XXX) and delimiter (in this case it's space character, but Microsoft allows using other chars like '.') and have you extension ignore prefix and delimiter (PostBudgetJournal instead of XXXPostBudgetJournal).

**Comment by RasmusTidselbak** [comment]
Thank you for the suggestion :)

I'll see if I can create a setting, which allow you to ignore a specific prefix.

**Comment by RasmusTidselbak** [comment]
I've added this suggestion to the current version 1.4.0
