### ISSUE TITLE
RecordRef should be placed before InStream/OutStream

### ISSUE THREAD

**Issue by jwikman** [RasmusTidselbak/al-var-helper#3]
When using the Sort Variables on an object that got variables of types RecordRef and InStream/OutStream the RecordRef variables is placed after the streams, but the AL CodeCop expects it to be before the streams.

Sort Variables (with complaints from the Code Analyzer):
```
    var
        IS: InStream;
        OS: OutStream;
        RecRef: RecordRef;
```
Correct way:
```
    var
        RecRef: RecordRef;
        IS: InStream;
        OS: OutStream;
```

**Comment by RasmusTidselbak** [comment]
I've fixed it with the latest release
