### ISSUE TITLE
Sort variables by type

### ISSUE THREAD

**Issue by AddEleven** [RasmusTidselbak/al-var-helper#7]
Is there functionality to sort variables based off type. EG: 

var
   TestBoolean: Boolean;
   Customer: Record Customer;

would become after sorting

var
   Customer: Record Customer;
   TestBoolean: Boolean;

**Comment by RasmusTidselbak** [comment]
AL-Var: Sort Variables does just that

**Comment by AddEleven** [comment]
Nice!
